In [118]:
import pandas as pd
data = pd.read_csv('Airbnb_Open_Data.csv')
data.head(5)
columns_to_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']
columns_to_drop = ['id', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license']
df = data[columns_to_keep]
df.rename(columns = {'NAME':'Name', 'host id':'host_id', 'host_identity_verified':'host_id_verified',
                       'host name':'host_name','neighbourhood group':'neighbourhood_group',
                      'country code':'country_code','room type':'room_type','Construction year':'construction_year',
                       'service fee':'service_fee', 'minimum nights':'minimum_nights','number of reviews':'number_of_reviews',
                       'last review':'last_review'} , inplace = True)
new_column_names = []
for i in df.columns:
  new_column_names.append(i.title())
df.columns = new_column_names
df.drop_duplicates(inplace = True)
df['Host_Id_Verified'] = df['Host_Id_Verified'].str.title()
df.isna().sum()
df.drop(columns = ['Last_Review'], inplace = True)
df.isna().sum()
df.dropna(inplace = True)
df.isna().sum()
df['Cancellation_Policy'] = df['Cancellation_Policy'].str.title()
df['Room_Type'] = df['Room_Type'].str.title()

df.head(1)
df['Construction_Year'] = df['Construction_Year'].astype('int')
df.dtypes
df.reset_index(inplace = True)

<ipython-input-118-398a19da1919>:2: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('Airbnb_Open_Data.csv')
<ipython-input-118-398a19da1919>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {'NAME':'Name', 'host id':'host_id', 'host_identity_verified':'host_id_verified',
<ipython-input-118-398a19da1919>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace = True)
<ipython-input-118-398a19da1919>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Host_Id_Verified'] = df['Host_Id_Verified'].str.title()
<ipython-input-118-398a19da1919>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns = ['Last_Review'], inplace = True)
<ipython-input-118-398a19da1919>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace = True)
<ipython-input-118-398a19da1919>:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Cancellation_Policy'] = df['Cancellation_Policy'].str.title()
<ipython-input-118-398a19da1919>:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Room_Type'] = df['Room_Type'].str.title()
<ipython-input-118-398a19da1919>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Construction_Year'] = df['Construction_Year'].astype('int')

In [122]:
df.dtypes

index                    int64
Name                    object
Host_Id                  int64
Host_Id_Verified        object
Host_Name               object
Neighbourhood_Group     object
Neighbourhood           object
Lat                    float64
Long                   float64
Country                 object
Country_Code            object
Instant_Bookable        object
Cancellation_Policy     object
Room_Type               object
Construction_Year        int64
Price                   object
Service_Fee             object
Minimum_Nights         float64
Number_Of_Reviews      float64
dtype: object

In [123]:
df = df.drop(columns = ['index'])

In [125]:
df.head(5)

,Name,Host_Id,Host_Id_Verified,Host_Name,Neighbourhood_Group,Neighbourhood,Lat,Long,Country,Country_Code,Instant_Bookable,Cancellation_Policy,Room_Type,Construction_Year,Price,Service_Fee,Minimum_Nights,Number_Of_Reviews
0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,Strict,Private Room,2020,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,Moderate,Entire Home/Apt,2007,$142,$28,30.0,45.0
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,Moderate,Entire Home/Apt,2009,$204,$41,10.0,9.0
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,Flexible,Entire Home/Apt,2013,$577,$115,3.0,74.0
4,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,Moderate,Private Room,2009,"$1,060",$212,45.0,49.0

In [128]:
type(df['Service_Fee'][15])

str

In [130]:
df["Price"] = df['Price'].str.replace("$", "")

In [131]:
df["Price"]

0          966
1          142
2          204
3          577
4        1,060
          ...
99337      822
99338      455
99339    1,078
99340      103
99341      982
Name: Price, Length: 99342, dtype: object

In [132]:
df["Price"] = df["Price"].str.replace(",", "")

In [133]:
df["Price"]

0         966
1         142
2         204
3         577
4        1060
         ...
99337     822
99338     455
99339    1078
99340     103
99341     982
Name: Price, Length: 99342, dtype: object

In [137]:
df["Price"] = df["Price"].str.replace(" ", "")
type(df["Price"])

pandas.core.series.Series

In [138]:
df["Price"].astype(int)

0         966
1         142
2         204
3         577
4        1060
         ...
99337     822
99338     455
99339    1078
99340     103
99341     982
Name: Price, Length: 99342, dtype: int64

In [139]:
df.head(1)

,Name,Host_Id,Host_Id_Verified,Host_Name,Neighbourhood_Group,Neighbourhood,Lat,Long,Country,Country_Code,Instant_Bookable,Cancellation_Policy,Room_Type,Construction_Year,Price,Service_Fee,Minimum_Nights,Number_Of_Reviews
0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,Strict,Private Room,2020,966,$193,10.0,9.0

In [140]:
df["Service_Fee"] = df["Service_Fee"].str.replace("$,  ", "")

In [143]:
df["Service_Fee"] = df["Service_Fee"].str.replace(",", "")

In [145]:
df["Service_Fee"] = df["Service_Fee"].str.replace("$", "")

In [147]:
df["Service_Fee"].astype(int)

0        193
1         28
2         41
3        115
4        212
        ...
99337    164
99338     91
99339    216
99340     21
99341    196
Name: Service_Fee, Length: 99342, dtype: int64

In [153]:
df['Price'] = df["Price"].astype('int')

In [154]:
df['Service_Fee'] = df["Service_Fee"].astype('int')

In [155]:
df.dtypes

Name                    object
Host_Id                  int64
Host_Id_Verified        object
Host_Name               object
Neighbourhood_Group     object
Neighbourhood           object
Lat                    float64
Long                   float64
Country                 object
Country_Code            object
Instant_Bookable        object
Cancellation_Policy     object
Room_Type               object
Construction_Year        int64
Price                    int64
Service_Fee              int64
Minimum_Nights         float64
Number_Of_Reviews      float64
dtype: object

In [156]:
df.head(1)

,Name,Host_Id,Host_Id_Verified,Host_Name,Neighbourhood_Group,Neighbourhood,Lat,Long,Country,Country_Code,Instant_Bookable,Cancellation_Policy,Room_Type,Construction_Year,Price,Service_Fee,Minimum_Nights,Number_Of_Reviews
0,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,Strict,Private Room,2020,966,193,10.0,9.0

In [158]:
df.to_csv('Airbnb_Open_Data_Cleaned.csv', index = False)